### ISSUE TITLE
OrderDetailReport renders blank on local instance

### ISSUE THREAD

**Issue by korlu** [volkanceylan/Serenity#2046]
First of all, I want to thank you for this great framework. 

I created a new project and included all sample projects, every thing is working fine except the OrderDetailReport (using the inline-action print-invoice on each row).

![blankreport](https://cloud.githubusercontent.com/assets/14118008/23816043/a40ba090-05b8-11e7-9d1c-48e4dd8f9a13.png)

I appreciate your help.
Thank you!

**Comment by Junariz** [comment]
By first, check you　can get order detail report  on HTML exactly.
http://localhost:(your debug IIS port#)/Report/Render?key=Northwind.OrderDetail&opt=%7B%22OrderID%22%3A11077%7D&print=1

next, invalidate access permission for HTML Page, remark 

[RequiredPermission(PermissionKeys.General)] on .\Module\Northwind\Order\OrderDetailReport.cs

and check your wkhtmltopdf.exe can convert HTML to PDF exactly, type below


at (Yout Project Path)\bin

wkhtmltopdf.exe --disable-smart-shrinking --page-size A4 --print-media-type --background  "http://localhost:(Your ISS port)/Report/Render?key=Northwind.OrderDetail&opt=%7B%22OrderID%22%3A11077%7D&print=1" C:\Users\user\AppData\Local\Temp\tmp558.pdf

Loading pages (1/6)
...
Done

(this will output C:\Users\user\AppData\Local\Temp\tmp558.pdf)

if you find message below
"Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load"
wkhtmltopdf would be fail get HTML report, then you can see only title and date will appear on PDF...

**Comment by Junariz** [comment]
.. it is the continuation of the previous Article.

If you can confirm "a disposed ResourceObject's NetworkAccessManager" error, I anticipate that the trouble will depend on the woff font..
I mean, wkhtmltopdf.exe seems to have a some problems to render WOFF font format..

see URL below,
https://blog.shaharia.com/use-google-web-fonts-for-wkhtmltopdf-tools-to-convert-html-to-pdf/

OrderDetailReport HTML has css below : 

-----
<link rel="icon" type="image/x-icon" href="/favicon.ico" />
    <link href="/Content/font-open-sans.css?v=_lyM_7sDAZstbPZ6aTr8rQ2" rel="stylesheet" type="text/css"/>
...
-----

and font-open-sans.css has reference to woff.

-----
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 300;
  src: local('Open Sans Light'), local('OpenSans-Light'), url(../fonts/OpenSansLight.woff) format('woff');
}
...
-----

So, I change font-open-sans.css "reference to woff" to "base64 encorded ttf embedded" below..

<font-open-sans.css>

@font-face {
    font-family: 'Open Sans';
    src: url(data:font/truetype;charset=utf-8;base64,AAEAAAATAQAABAAw..(LONG STRING, Encorded font)....) format('truetype');
    font-weight: normal;
    font-style: normal;
}
/* remark exsting CSS
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 300;
  src: local('Open Sans Light'), local('OpenSans-Light'), url(../fonts/OpenSansLight.woff) format('woff');
}
@font-face {
....

*/

I encode font by :
https://www.fontsquirrel.com/tools/webfont-generator

so I can get OrderDetai PDF.

![orderdetailpdf_output](https://cloud.githubusercontent.com/assets/26323684/23846192/998ce724-080f-11e7-8e9b-420936c94987.jpg)

**Comment by korlu** [comment]
Junariz, thanks your help. I tried the steps you suggested and yes, wkhtmltopdf.exe generates a standalone PDF file. But still didn't solve my original issue.

However, when I publish it to a local IIS server, everything works fine. So the issue seems to be isolated to IIS Express.

Thanks.
